version: "3.9"

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev_super_secret_change_me} # Cambia in produzione
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-gpt-oss:latest}
    ports:
      - "8005:8005"
    volumes:
      - ./data:/app/data:ro                       # Dati di input (seed, read-only)
      - ./backend/storage:/app/storage            # Storage persistente generale
      - ./backend/storage/prompts:/app/storage/prompts           # System prompts runtime
      - ./backend/storage/personalities:/app/storage/personalities # Personalities runtime
      - ./backend/storage/summary:/app/storage/summary           # Summary prompt runtime
      - ./backend/storage/welcome-guide:/app/storage/welcome-guide # Welcome & guides runtime
      - ./backend/models:/app/models              # Modelli
      - ./backend/config:/app/config              # Config
      - ./backend/.env:/app/.env:ro               # Env file

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5176:5175"
    depends_on:
      - backend
